// vue-test/src/components/AddTodo.vue
<template>
  <div>
    <form @submit="addTodo">
      <input type="text" v-model="title" name="title" placeholder="Add Todo...">
      <input type="submit" value="Submit" class="btn">
    </form>
  </div>
</template>

<script>
export default {
  name: "AddTodo",
  data() {
    return {
      title: ""
    };
  },
  methods: {
    addTodo(e) {
      e.preventDefault();
      const newTodo = {
        title: this.title,
        completed: false
      };

      this.$emit("add-todo", newTodo);

      this.title = "";
    }
  }
};
</script>

<style scoped>
form {
  display: flex;
}

input[type="text"] {
  flex: 10;
  padding: 5px;
}
input[type="submit"] {
  flex: 2;
}
</style>

// angular/angular-crash-todolist/src/app/components/add-todo/add-todo.component.ts
import { Component, OnInit, EventEmitter, Output } from '@angular/core';
import { Event } from '@angular/router';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.css']
})
export class AddTodoComponent implements OnInit {
  @Output() addTodo: EventEmitter<any> = new EventEmitter();

  title:string;

  constructor() { }

  ngOnInit(): void {
  }

  onSubmit() {
    const todo = {
      title:this.title,
      completed:false
    }

    this.addTodo.emit(todo);

  }

}

<form class="form" (ngSubmit)="onSubmit()">
    <input 
        type="text" 
        name="title" 
        [(ngModel)] ="title"
        placeholder="Add Todo..."
    >
    <input type="submit" value="Submit" class="btn">
</form>
